version: '3.9'

services:
  worker-demo-app:
    container_name: worker-demo-app
    build:
      dockerfile: dev.Dockerfile
      context: .
    networks:
      - worker-demo
    ports:
      - "8080:8080"
      - "8081:8081"
    expose:
      - "8080"
      - "8081"
    volumes:
      - .:/app
    env_file:
      - .env

  worker-demo-pubsub:
    container_name: worker-demo-pubsub
    image: messagebird/gcloud-pubsub-emulator:latest
    networks:
      - worker-demo
    ports:
      - "8681:8681"
    env_file:
      - .env
    environment:
      - PUBSUB_PROJECT1=${PUBSUB_PROJECT_ID:-demo-project},${PUBSUB_TOPIC_ID:-demo-topic}:${PUBSUB_SUBSCRIPTION_ID:-demo-subscription}

  worker-demo-pubsub-ui:
    container_name: worker-demo-pubsub-ui
    image: echocode/gcp-pubsub-emulator-ui:latest
    networks:
      - worker-demo
    ports:
      - "8680:8680"
    expose:
      - "8680"
    env_file:
      - .env
    environment:
      - PUBSUB_EMULATOR_HOST=${PUBSUB_EMULATOR_HOST:-worker-demo-pubsub:8681}
      - GCP_PROJECT_IDS=${PUBSUB_PROJECT_ID:-demo-project}

  worker-demo-jaeger:
    container_name: worker-demo-jaeger
    image: jaegertracing/all-in-one
    networks:
      - worker-demo
    ports:
      - "4317:4317"
      - "16686:16686"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

networks:
  worker-demo:
    driver: bridge