app:
  debug: true
modules:
  log:
    output: test
  trace:
    processor:
      type: test
  gcppubsub:
    project:
      id: test-project
config:
  topic:
    id: test-topic
  subscription:
    id: test-subscription
