app:
  debug: true
modules:
  mcp:
    server:
      log:
        request: true
        response: true
      trace:
        request: true
        response: true
  log:
    level: debug
    output: console
  trace:
    processor:
      type: otlp-grpc
      options:
        host: ${OTLP_COLLECTOR_HOST}:${OTLP_COLLECTOR_PORT}
