version: '3.9'

services:
  grpc-demo-app:
    container_name: grpc-demo-app
    build:
      dockerfile: dev.Dockerfile
      context: .
    networks:
      - grpc-demo
    ports:
      - "50051:50051"
      - "8081:8081"
    expose:
      - "50051"
      - "8081"
    volumes:
      - .:/app
    env_file:
      - .env

networks:
  grpc-demo:
    driver: bridge
