app:
  name: http-demo-app
  version: 0.1.0
modules:
  core:
    server:
      port: 8081
      dashboard:
        enabled: true
        overview:
          app_env: true
          app_debug: true
          app_version: true
          log_level: true
          log_output: true
          trace_sampler: true
          trace_processor: true
      metrics:
        expose: true
        collect:
          enabled: true
        normalize:
          request_path: true
          response_status: true
      healthcheck:
        startup:
          expose: true
        readiness:
          expose: true
        liveness:
          expose: true
      debug:
        config:
          expose: true
        pprof:
          expose: true
        routes:
          expose: true
        stats:
          expose: true
        build:
          expose: true
        modules:
          expose: true
  http:
    server:
      port: 8080
      trace:
        enabled: true
      metrics:
        collect:
          enabled: true
        normalize:
          request_path: true
          response_status: true
      templates:
        enabled: true
        path: templates/*.html
  orm:
    driver: mysql
    dsn: ${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/${MYSQL_DATABASE}?parseTime=true
    log:
      enabled: true
      level: info
      values: true
    trace:
      enabled: true
      values: true
  log:
    level: debug
config:
  authentication:
    enabled: false
    secret: super-secret
  dashboard:
    title: Yokai HTTP demo
  service:
    gopher:
      log: true
      trace: true
