app:
  debug: false
modules:
  core:
    server:
      metrics:
        collect:
          enabled: false
      debug:
        pprof:
          expose: false
        stats:
          expose: false
  orm:
    config:
      prepare_stmt: true
  log:
    level: info
    output: stdout
