app:
  debug: true
modules:
  orm:
    driver: sqlite
    dsn: ":memory:"
  log:
    output: test
  trace:
    processor:
      type: test
config:
  authentication:
    enabled: ${AUTH_ENABLED}
    secret: ${AUTH_SECRET}
  dashboard:
    title: Test dashboard title
