app:
  debug: true
modules:
  sql:
    driver: sqlite
    dsn: ":memory:"
    migrations:
      stdout: false
  log:
    output: test
  trace:
    processor:
      type: test
config:
  authentication:
    enabled: ${AUTH_ENABLED}
    secret: ${AUTH_SECRET}
  dashboard:
    title: Test dashboard title
  seed:
    gophers:
      alice: architect
      bob: builder
      carl: carpenter
