app:
  debug: true
modules:
  gomysqlserver:
    config:
      protocol: bufconn
  sql:
    dsn: "user:password@mysqlmemory(bufconn)/db?parseTime=true"
    migrations:
        stdout: false
  log:
    output: test
  trace:
    processor:
      type: test
config:
  authentication:
    enabled: ${AUTH_ENABLED}
    secret: ${AUTH_SECRET}
  dashboard:
    title: Test dashboard title
  seed:
    gophers:
      alice: frontend
      bob: backend
      carl: backend
      dan: frontend
      elvis: backend
