// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
)

type Gopher struct {
	ID   int32          `json:"id"`
	Name string         `json:"name"`
	Job  sql.NullString `json:"job"`
}
