// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateGopher(ctx context.Context, arg CreateGopherParams) (sql.Result, error)
	DeleteGopher(ctx context.Context, id int32) error
	GetGopher(ctx context.Context, id int32) (Gopher, error)
	ListGophers(ctx context.Context) ([]Gopher, error)
}

var _ Querier = (*Queries)(nil)
